name: idp
recipe: drupal9
config:
  webroot: web
# services:
#   appserver:
#     run:
#       - composer install
#       - drush site-install standard --db-url=mysql://drupal9:drupal9@database/drupal9 -y
